"""db init

Revision ID: 7ee39bc1f191
Revises: 
Create Date: 2024-10-06 15:48:49.755271

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7ee39bc1f191"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("senderId", sa.Integer(), nullable=False),
        sa.Column("nickname", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("balanceRub", sa.Integer(), nullable=False),
        sa.Column("balanceGeneration", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("senderId"),
    )
    op.create_table(
        "action",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("senderId", sa.Integer(), nullable=False),
        sa.Column("actionStart", sa.Integer(), nullable=False),
        sa.Column("actionPayment", sa.Integer(), nullable=False),
        sa.Column("actionGeneration", sa.Integer(), nullable=False),
        sa.Column("actionLowGeneration", sa.Integer(), nullable=False),
        sa.Column("actionHighGeneration", sa.Integer(), nullable=False),
        sa.Column("actionSendUrl", sa.Integer(), nullable=False),
        sa.Column("actionSendPictures", sa.Integer(), nullable=False),
        sa.Column("actionSendDescription", sa.Integer(), nullable=False),
        sa.Column("actionSendType", sa.Integer(), nullable=False),
        sa.Column("actionCheckBalance", sa.Integer(), nullable=False),
        sa.Column("actionSuccessGeneration", sa.Integer(), nullable=False),
        sa.Column("actionSuccessPayment", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["senderId"],
            ["user.senderId"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("action")
    op.drop_table("user")
    # ### end Alembic commands ###
